In [ ]:
%pip install -q kagglehub
import kagglehub
import pandas as pd
import os

path = kagglehub.dataset_download(
    "olistbr/brazilian-ecommerce"
)

print(path)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.
C:\Users\Usuario\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2

In [2]:
files = os.listdir(path)

for file in files:
    print(file)

olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_orders_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [ ]:
#asi se cargan las tablas en un diccionario, donde la clave es el nombre de la tabla y el valor es el DataFrame

tables = {}
for file in files:
    if file.endswith(".csv"):
        table_name = file.replace(".csv", "")
        table_path = os.path.join(path, file)
        tables[table_name] = pd.read_csv(table_path)
        print(f"Loaded table: {table_name}")

tables["olist_customers_dataset"].head()

Loaded table: olist_customers_dataset
Loaded table: olist_geolocation_dataset
Loaded table: olist_orders_dataset
Loaded table: olist_order_items_dataset
Loaded table: olist_order_payments_dataset
Loaded table: olist_order_reviews_dataset
Loaded table: olist_products_dataset
Loaded table: olist_sellers_dataset
Loaded table: product_category_name_translation

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [6]:
#ahora vamos a ver el tamanio de las tablas
for name, df in tables.items():
    print(f"Table: {name}, Rows: {df.shape[0]}, Columns: {df.shape[1]}")

Table: olist_customers_dataset, Rows: 99441, Columns: 5
Table: olist_geolocation_dataset, Rows: 1000163, Columns: 5
Table: olist_orders_dataset, Rows: 99441, Columns: 8
Table: olist_order_items_dataset, Rows: 112650, Columns: 7
Table: olist_order_payments_dataset, Rows: 103886, Columns: 5
Table: olist_order_reviews_dataset, Rows: 99224, Columns: 7
Table: olist_products_dataset, Rows: 32951, Columns: 9
Table: olist_sellers_dataset, Rows: 3095, Columns: 4
Table: product_category_name_translation, Rows: 71, Columns: 2

In [ ]:
#primer resumen basico automatico, seria un data quality overview, que nos da una idea de la calidad de los datos y de la estructura de las tablas
summary = {}

for name, df in tables.items():
    summary[name] = {
        "rows": df.shape[0],
        "columns": df.shape[1],
        "missing_values": df.isnull().sum().sum(),
        "duplicate_rows": df.duplicated().sum(),
        "data_types": df.dtypes.value_counts().to_dict()
    }
summary_df = pd.DataFrame.from_dict(summary, orient='index')
summary_df

,rows,columns,missing_values,duplicate_rows,data_types
olist_customers_dataset,99441,5,0,0,"{str: 4, int64: 1}"
olist_geolocation_dataset,1000163,5,0,261831,"{float64: 2, str: 2, int64: 1}"
olist_orders_dataset,99441,8,4908,0,{str: 8}
olist_order_items_dataset,112650,7,0,0,"{str: 4, float64: 2, int64: 1}"
olist_order_payments_dataset,103886,5,0,0,"{str: 2, int64: 2, float64: 1}"
olist_order_reviews_dataset,99224,7,145903,0,"{str: 6, int64: 1}"
olist_products_dataset,32951,9,2448,0,"{float64: 7, str: 2}"
olist_sellers_dataset,3095,4,0,0,"{str: 3, int64: 1}"
product_category_name_translation,71,2,0,0,{str: 2}

In [9]:
orders = tables["olist_orders_dataset"]
orders["order_id"].duplicated().sum()

np.int64(0)

In [10]:
items = tables["olist_order_items_dataset"]
items["order_id"].duplicated().sum()

np.int64(13984)